FROM node:22.20.0 AS build
WORKDIR /app
COPY package*.json package-lock.json ./
RUN npm install
COPY . ./
RUN npm run build --prod

FROM nginx:alpine
COPY --from=build /app/dist/angular/browser /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
